#!/bin/bash
# FibreFlow Agent Initialization Script
# Generated by: Harness Initializer Agent
# Agent: knowledge_base

set -e  # Exit on error

AGENT_NAME="knowledge_base"
AGENT_DIR="agents/${AGENT_NAME}"
TEST_FILE="tests/test_${AGENT_NAME}.py"
REPO_DIR="~/velocity-fibre-knowledge"

echo "Initializing FibreFlow Agent: ${AGENT_NAME}"
echo "=========================================="

# Create agent directory structure
echo "Creating directory structure..."
mkdir -p "${AGENT_DIR}"
mkdir -p "${AGENT_DIR}/tools"
touch "${AGENT_DIR}/__init__.py"
touch "${AGENT_DIR}/tools/__init__.py"

# Create placeholder agent.py if not exists
if [ ! -f "${AGENT_DIR}/agent.py" ]; then
    echo "Creating agent.py placeholder..."
    cat > "${AGENT_DIR}/agent.py" << 'EOF'
#!/usr/bin/env python3
"""
KnowledgeBase Agent - FibreFlow Specialized Agent
"""
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from shared.base_agent import BaseAgent


class KnowledgeBaseAgent(BaseAgent):
    """Knowledge Base Agent for documentation management."""

    def define_tools(self):
        return []

    def execute_tool(self, tool_name, tool_input):
        return "{}"

    def get_system_prompt(self):
        return """You are a Knowledge Base Agent responsible for 
        creating and maintaining comprehensive developer documentation 
        for the Velocity Fibre ecosystem."""

EOF
fi

# Create knowledge base repository if not exists
echo "Setting up velocity-fibre-knowledge repository..."
mkdir -p "${REPO_DIR}"
mkdir -p "${REPO_DIR}/docs"
mkdir -p "${REPO_DIR}/scripts"
touch "${REPO_DIR}/mkdocs.yml"
touch "${REPO_DIR}/README.md"

# Initialize git repository
if [ ! -d "${REPO_DIR}/.git" ]; then
    echo "Initializing git repository..."
    cd "${REPO_DIR}"
    git init
    git add .
    git commit -m "Initial commit: Velocity Fibre Knowledge Base setup"
    cd -
fi

# Verify Python environment
echo "Verifying Python environment..."
if [ ! -d "venv" ]; then
    echo "ERROR: Virtual environment not found!"
    exit 1
fi

# Check BaseAgent accessible
echo "Checking BaseAgent..."
./venv/bin/python3 -c "from shared.base_agent import BaseAgent; print('✅ BaseAgent accessible')" || exit 1

# Ensure required directories exist
REQUIRED_DIRS=(
    ".claude/skills"
    "tests"
    "scripts"
    "agents/knowledge_base"
)

for dir in "${REQUIRED_DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
        echo "Created directory: $dir"
    fi
done

echo "=========================================="
echo "✅ Agent initialization complete"
echo "Agent directory: ${AGENT_DIR}"
echo "Repo directory: ${REPO_DIR}"
echo "Ready for coding agent sessions"

# Make script executable
chmod +x "$0"