#!/bin/bash
# FibreFlow Knowledge Base Agent Initialization Script
# Generated by: Harness Initializer Agent

set -e  # Exit on error

AGENT_NAME="knowledge_base"
AGENT_DIR="agents/${AGENT_NAME}"
KNOWLEDGE_BASE_DIR="~/velocity-fibre-knowledge"

echo "Initializing FibreFlow Knowledge Base Agent"
echo "=========================================="

# Ensure agent directory exists
echo "Creating agent directory structure..."
mkdir -p "${AGENT_DIR}"
touch "${AGENT_DIR}/__init__.py"

# Create placeholder agent.py
echo "Creating agent.py placeholder..."
cat > "${AGENT_DIR}/agent.py" << 'EOF'
#!/usr/bin/env python3
"""
KnowledgeBase Agent - FibreFlow Specialized Agent

Manages creation and deployment of centralized developer knowledge base.
"""
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from shared.base_agent import BaseAgent


class KnowledgeBaseAgent(BaseAgent):
    """
    Autonomous agent for setting up and maintaining the Velocity Fibre 
    developer knowledge base.
    """

    def define_tools(self):
        """
        Define tools for the knowledge base agent.
        Will be replaced during implementation.
        """
        return []

    def execute_tool(self, tool_name, tool_input):
        """
        Execute knowledge base agent tools.
        Placeholder for future implementation.
        """
        return "{}"

    def get_system_prompt(self):
        """
        Get system prompt describing the knowledge base agent's purpose.
        """
        return """You are a FibreFlow Knowledge Base Agent responsible for:
        1. Creating a centralized developer documentation system
        2. Documenting servers, apps, databases, and procedures
        3. Setting up web deployment for docs.fibreflow.app
        4. Creating searchable, version-controlled knowledge base
        """
EOF

# Create knowledge base repository structure
echo "Creating velocity-fibre-knowledge repository..."
mkdir -p "${KNOWLEDGE_BASE_DIR}/docs/servers"
mkdir -p "${KNOWLEDGE_BASE_DIR}/docs/apps/fibreflow"
mkdir -p "${KNOWLEDGE_BASE_DIR}/docs/apps/qfieldcloud"
mkdir -p "${KNOWLEDGE_BASE_DIR}/docs/apps/wa-monitor"
mkdir -p "${KNOWLEDGE_BASE_DIR}/docs/databases"
mkdir -p "${KNOWLEDGE_BASE_DIR}/scripts"

# Initialize git repository
echo "Initializing git repository..."
cd "${KNOWLEDGE_BASE_DIR}"
git init
git add .
git commit -m "Initial commit: FibreFlow Knowledge Base repository setup"

# Verify Python environment
echo "Verifying Python environment..."
if [ ! -d "venv" ]; then
    echo "ERROR: Virtual environment not found!"
    exit 1
fi

# Check BaseAgent accessible
echo "Checking BaseAgent..."
./venv/bin/python3 -c "from shared.base_agent import BaseAgent; print('✅ BaseAgent accessible')" || exit 1

echo "=========================================="
echo "✅ Knowledge Base Agent Initialization Complete"
echo "Agent Directory: ${AGENT_DIR}"
echo "Knowledge Base Repository: ${KNOWLEDGE_BASE_DIR}"
echo "Ready for implementation phases"