#!/bin/bash
# FibreFlow Knowledge Base Agent Initialization Script
# Generated by: Harness Initializer Agent

set -e  # Exit on error

AGENT_NAME="knowledge_base"
AGENT_DIR="agents/${AGENT_NAME}"
KNOWLEDGE_BASE_REPO="~/velocity-fibre-knowledge"

echo "Initializing FibreFlow Knowledge Base Agent"
echo "=========================================="

# Create directory structure for agent
echo "Creating agent directory structure..."
mkdir -p "${AGENT_DIR}"
touch "${AGENT_DIR}/__init__.py"

# Create placeholder agent.py if not exists
if [ ! -f "${AGENT_DIR}/agent.py" ]; then
    echo "Creating agent.py placeholder..."
    cat > "${AGENT_DIR}/agent.py" << 'EOF'
#!/usr/bin/env python3
"""
Knowledge Base Agent - FibreFlow Specialized Agent
Manages documentation repository and generation
"""
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from shared.base_agent import BaseAgent
from typing import List, Dict, Any


class KnowledgeBaseAgent(BaseAgent):
    """
    Knowledge Base Agent for Velocity Fibre documentation
    Responsible for generating, maintaining, and deploying developer documentation
    """

    def get_system_prompt(self) -> str:
        """
        Generate system prompt for Knowledge Base Agent
        
        Returns:
            str: Detailed system prompt describing agent's role
        """
        return """You are a Knowledge Base Agent for Velocity Fibre.

        Your primary responsibilities include:
        - Creating and maintaining comprehensive developer documentation
        - Generating documentation for servers, apps, databases
        - Setting up MkDocs web interface
        - Automating documentation updates
        - Integrating with Claude Code skills

        You work methodically, ensuring:
        - Accuracy of technical documentation
        - Clear and comprehensive information
        - Automated updates and deployments
        """

    def define_tools(self) -> List[Dict[str, Any]]:
        """
        Define tools available for Knowledge Base Agent
        
        Returns:
            List of tool definitions
        """
        return [
            {
                "name": "create_repo_structure",
                "description": "Initialize knowledge base repository",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "base_path": {"type": "string"},
                        "create_git": {"type": "boolean", "default": True}
                    },
                    "required": ["base_path"]
                }
            }
        ]

    def execute_tool(self, tool_name: str, tool_input: Dict[str, Any]) -> str:
        """
        Execute specified tool with given input
        
        Args:
            tool_name (str): Name of tool to execute
            tool_input (Dict): Input parameters for tool
        
        Returns:
            str: Tool execution result
        """
        # TODO: Implement tool execution logic
        return '{"status": "not_implemented", "message": "Tool execution pending implementation"}'
EOF
fi

# Create velocity-fibre-knowledge repo structure
echo "Creating knowledge base repository structure..."
mkdir -p "${KNOWLEDGE_BASE_REPO}/docs/"{servers,apps,databases,skills,procedures}
mkdir -p "${KNOWLEDGE_BASE_REPO}/scripts"
mkdir -p "${KNOWLEDGE_BASE_REPO}/site"

# Create initial README.md
echo "Creating README.md..."
cat > "${KNOWLEDGE_BASE_REPO}/README.md" << 'EOF'
# Velocity Fibre Knowledge Base

Centralized developer documentation for the Velocity Fibre ecosystem.

## Quick Start

\`\`\`bash
# Clone repository
git clone <repo_url> velocity-fibre-knowledge

# Navigate to directory
cd velocity-fibre-knowledge

# Build documentation
mkdocs build
\`\`\`

More details coming soon.
EOF

# Verify Python environment
echo "Verifying Python environment..."
if [ ! -d "venv" ]; then
    echo "ERROR: Virtual environment not found!"
    exit 1
fi

# Check BaseAgent accessible
echo "Checking BaseAgent..."
./venv/bin/python3 -c "from shared.base_agent import BaseAgent; print('✅ BaseAgent accessible')" || exit 1

# Git initialization
echo "Initializing git repository..."
cd "${KNOWLEDGE_BASE_REPO}"
git init
git add .
git commit -m "Initial commit: Knowledge Base repository setup"

echo "=========================================="
echo "✅ Knowledge Base Agent Initialization Complete"
echo "Agent directory: ${AGENT_DIR}"
echo "Knowledge Base Repository: ${KNOWLEDGE_BASE_REPO}"
echo "Ready for coding agent sessions"